export const ADULT_PINS = [
  // TRUE CRIME
  {
    id: "tc_001",
    n: "2G Brig Street",
    l: [54.11371, -3.218448],
    i: "🔪",
    set: "adult",
    category: "true_crime",
    zone: "Residential",
    event: "The Hammer Murder (Nellie Pearson)",
  },
  {
    id: "tc_002",
    n: "8 Bacchus Street",
    l: [54.113063, -3.237478],
    i: "🔪",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "Lydia Green Murder (The Hoxton Tragedy)",
  },
  {
    id: "tc_003",
    n: "Bacchus St / Hindpool Corner",
    l: [54.114309, -3.235831],
    i: "🔪",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "Joseph Baines Christmas Eve Murder",
  },
  {
    id: "tc_004",
    n: "Forsyth Street (Back Alley)",
    l: [54.114721, -3.23521],
    i: "🩸",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: 'The "Forgotten Baby" Dog Discovery',
  },
  {
    id: "tc_005",
    n: "Marsh St (Salthouse End)",
    l: [54.109267, -3.215243],
    i: "🩸",
    set: "adult",
    category: "true_crime",
    zone: "Residential",
    event: 'The "Salthouse Bundle" Baby Discovery',
  },
  {
    id: "tc_006",
    n: "Barrow Market (Old Site)",
    l: [54.111491, -3.227258],
    i: "🔪",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: "William Miller (The Butcher) Arrest",
  },
  {
    id: "tc_007",
    n: "Berrymede Road",
    l: [54.118912, -3.210445],
    i: "🕵️",
    set: "adult",
    category: "true_crime",
    zone: "Outskirts",
    event: 'The "Jack the Stripper" Connection',
  },
  {
    id: "tc_008",
    n: "Dalton Road (Alley)",
    l: [54.111966, -3.2254],
    i: "⚰️",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: 'The "Hush Money" Execution Spot',
  },
  {
    id: "tc_009",
    n: "The Strand (Waterfront)",
    l: [54.110245, -3.23158],
    i: "⚰️",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Smuggler’s End Execution",
  },
  {
    id: "tc_010",
    n: "Greengate Street",
    l: [54.112795, -3.220397],
    i: "🔪",
    set: "adult",
    category: "true_crime",
    zone: "Residential",
    event: "The Shilling Robbery Murder Site",
  },
  {
    id: "tc_011",
    n: "Marsh Street (Middle)",
    l: [54.112047, -3.217027],
    i: "⚔️",
    set: "adult",
    category: "true_crime",
    zone: "Residential",
    event: 'The "Knife & Steel" Riot of 1890',
  },
  {
    id: "tc_012",
    n: "Duke Street (Lower)",
    l: [54.110031, -3.225251],
    i: "🕵️",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: 'The "Gentleman Burglar" Hideout',
  },
  {
    id: "tc_013",
    n: "Hoxton Slums (Hindpool)",
    l: [54.11405, -3.23652],
    i: "⚔️",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: 'The Bedroom Riot / "Hot Bed" Fight',
  },
  {
    id: "tc_014",
    n: "Custom House / Hindpool Rd",
    l: [54.112827, -3.233416],
    i: "🩸",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: 'The "Blood Cobbles" Riot Site',
  },
  {
    id: "tc_015",
    n: "Railway Hotel (Old Site)",
    l: [54.115712, -3.228225],
    i: "☠️",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: "The Barrow Poisoning Mystery",
  },
  {
    id: "tc_016",
    n: "Hindpool (Tiger Mural)",
    l: [54.117359, -3.23648],
    i: "🚫",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: 'The Police "No-Go" Boundary',
  },
  {
    id: "tc_017",
    n: "Old Police Station",
    l: [54.11118, -3.227026],
    i: "🚔",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: 'The "Peelers" Siege Site',
  },
  {
    id: "tc_018",
    n: "Piel Castle (Dungeon)",
    l: [54.062336, -3.173362],
    i: "⛓️",
    set: "adult",
    category: "true_crime",
    zone: "Abbey/Ruins",
    event: "The Lambert Simnel Rebel Site",
  },
  {
    id: "tc_019",
    n: "The Ship Inn (Piel)",
    l: [54.064046, -3.172852],
    i: "💰",
    set: "adult",
    category: "true_crime",
    zone: "Walney/Coastal",
    event: "The Shipwreck Gold Secret",
  },
  {
    id: "tc_020",
    n: "Walney West Shore",
    l: [54.11621, -3.27253],
    i: "🕯️",
    set: "adult",
    category: "true_crime",
    zone: "Walney/Coastal",
    event: 'The "Wreckers" False Lantern Site',
  },
  {
    id: "tc_021",
    n: "Lifeboat Station (Old)",
    l: [54.064046, -3.172852],
    i: "⚓",
    set: "adult",
    category: "true_crime",
    zone: "Walney/Coastal",
    event: "The 1890 Crew Tragedy",
  },
  {
    id: "tc_022",
    n: "Cornwallis St (Walls)",
    l: [54.111792, -3.228755],
    i: "🪓",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: 'The Convict "V" Markings',
  },
  {
    id: "tc_023",
    n: "Hindpool / Abbey Corner",
    l: [54.1142, -3.230979],
    i: "🍞",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: "The Loaf of Bread Murder",
  },

  // CONSPIRACY
  {
    id: "con_001",
    n: "DDH Hall (BAE Systems)",
    l: [54.109263, -3.239847],
    i: "🛸",
    set: "adult",
    category: "conspiracy",
    zone: "Docks",
    event: 'The "Phantom Crane" Suicide Site',
  },
  {
    id: "con_002",
    n: "Steel Company HQ",
    l: [54.11252, -3.22684],
    i: "📁",
    set: "adult",
    category: "conspiracy",
    zone: "Civic",
    event: 'The "Silence Money" Envelopes',
  },
  {
    id: "con_003",
    n: "The Jetty (Walney)",
    l: [54.119381, -3.271118],
    i: "🌫️",
    set: "adult",
    category: "conspiracy",
    zone: "Walney/Coastal",
    event: 'The Stowaway "Return" Point',
  },
  {
    id: "con_004",
    n: "Buoy Wharf",
    l: [54.10214, -3.23952],
    i: "🛸",
    set: "adult",
    category: "conspiracy",
    zone: "Docks",
    event: 'The "Floating Mystery" Tie-up',
  },
  {
    id: "con_005",
    n: "Submarine Slipway (Old)",
    l: [54.10154, -3.23321],
    i: "🕵️",
    set: "adult",
    category: "conspiracy",
    zone: "Docks",
    event: 'The Armed Guard "Spy" Post',
  },
  {
    id: "con_006",
    n: "The Forum (Duke St)",
    l: [54.112121, -3.227529],
    i: "☣️",
    set: "adult",
    category: "conspiracy",
    zone: "Civic",
    event: "2002 Legionnaires' Outbreak",
  },
  {
    id: "con_007",
    n: "Furness General Hospital",
    l: [54.136744, -3.210349],
    i: "🏥",
    set: "adult",
    category: "conspiracy",
    zone: "Civic",
    event: "Maternity Cover-up Scandal",
  },
  {
    id: "con_008",
    n: "CQC Office (Old Site)",
    l: [54.11352, -3.22414],
    i: "🗂️",
    set: "adult",
    category: "conspiracy",
    zone: "Civic",
    event: 'The "Deleted File" Shredder Room',
  },
  {
    id: "con_009",
    n: "Public Baths (Abbey Rd)",
    l: [54.114949, -3.229983],
    i: "🤝",
    set: "adult",
    category: "conspiracy",
    zone: "Civic",
    event: 'The "Grey Contract" Meeting Room',
  },
  {
    id: "con_010",
    n: "Barrow Library",
    l: [54.114356, -3.231339],
    i: "📚",
    set: "adult",
    category: "conspiracy",
    zone: "Civic",
    event: '1945 "Red File" Hiding Spot',
  },
  {
    id: "con_011",
    n: "Customs House",
    l: [54.112978, -3.233288],
    i: "💼",
    set: "adult",
    category: "conspiracy",
    zone: "Civic",
    event: 'The "Blind Eye" Bribe Spot',
  },
  {
    id: "con_012",
    n: "Walney Airfield Bunker",
    l: [54.120865, -3.256751],
    i: "🪖",
    set: "adult",
    category: "conspiracy",
    zone: "Walney/Coastal",
    event: 'Last Stand "Suicide" Bunker',
  },
  {
    id: "con_013",
    n: "West Shore Tower",
    l: [54.13052, -3.27014],
    i: "👁️",
    set: "adult",
    category: "conspiracy",
    zone: "Walney/Coastal",
    event: "Government Town-Watch Post",
  },
  {
    id: "con_014",
    n: "Municipal Buildings",
    l: [54.11152, -3.22854],
    i: "🔥",
    set: "adult",
    category: "conspiracy",
    zone: "Civic",
    event: "Slum Clearance Evidence Burn",
  },
  {
    id: "con_015",
    n: "Record Office (Duke St)",
    l: [54.11184, -3.22685],
    i: "🗺️",
    set: "adult",
    category: "conspiracy",
    zone: "Civic",
    event: 'The "Secret Map" Archive',
  },
  {
    id: "con_016",
    n: "Main Yard Entrance",
    l: [54.10921, -3.23941],
    i: "🚧",
    set: "adult",
    category: "conspiracy",
    zone: "Docks",
    event: "Government ID Check Post",
  },
  {
    id: "con_017",
    n: "Telegram Office",
    l: [54.11142, -3.22784],
    i: "📡",
    set: "adult",
    category: "conspiracy",
    zone: "Civic",
    event: '"Hollow Knock" Message Center',
  },
  {
    id: "con_018",
    n: "Dock Gate 1",
    l: [54.10821, -3.22741],
    i: "🚢",
    set: "adult",
    category: "conspiracy",
    zone: "Docks",
    event: 'Forbidden "Gov Property" Zone',
  },
  {
    id: "con_019",
    n: "Ghost Path Gate (Abbey Rd)",
    l: [54.140075, -3.200542],
    i: "👻",
    set: "adult",
    category: "conspiracy",
    zone: "Abbey/Ruins",
    event: 'The "White Lady" Waiting Spot',
  },

  // HISTORY
  {
    id: "hist_001",
    n: "Dock Museum (Graving)",
    l: [54.1124, -3.240276],
    i: "⚙️",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: "The Unsolved Riveter Murder",
  },
  {
    id: "hist_002",
    n: "Bridge Road Gates",
    l: [54.104823, -3.23345],
    i: "📜",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: 'WWI "White Feather" Shaming Site',
  },
  {
    id: "hist_003",
    n: "Michaelson Road",
    l: [54.105043, -3.230699],
    i: "🏭",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: "Asbestos Alley (The White Dust)",
  },
  {
    id: "hist_004",
    n: "North Slag Bank",
    l: [54.13315, -3.24307],
    i: "⛰️",
    set: "adult",
    category: "history",
    zone: "Industrial",
    event: 'The "Disappearance" Molten Hole',
  },
  {
    id: "hist_005",
    n: "Devonshire Dock",
    l: [54.102709, -3.232435],
    i: "⚓",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: 'The "Screaming Sub" Launch Site',
  },
  {
    id: "hist_006",
    n: "Shipyard Main Clock",
    l: [54.10651, -3.23214],
    i: "🕰️",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: 'The "Death Clock" (Shift Accidents)',
  },
  {
    id: "hist_007",
    n: "Old Ironworks Site",
    l: [54.11958, -3.23852],
    i: "🏭",
    set: "adult",
    category: "history",
    zone: "Industrial",
    event: "The Chimney Fall Tragedy",
  },
  {
    id: "hist_008",
    n: "North Gate (Bridge Rd)",
    l: [54.109439, -3.239407],
    i: "🛠️",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: "Young Charles’ Wagon Tragedy",
  },
  {
    id: "hist_009",
    n: "Barrow Island Blocks",
    l: [54.10152, -3.22814],
    i: "🏚️",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: 'The 3,000-man "Shanty" Slum Site',
  },
  {
    id: "hist_010",
    n: "Engine Sheds (Rail)",
    l: [54.11181, -3.21854],
    i: "💥",
    set: "adult",
    category: "history",
    zone: "Industrial",
    event: "The 1910 Boiler Explosion",
  },
  {
    id: "hist_011",
    n: "Vulcan Works (Hindpool)",
    l: [54.11582, -3.23412],
    i: "🔥",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: "The 1892 Riot Fire Marks",
  },
  {
    id: "hist_012",
    n: "Blast Furnace Site",
    l: [54.11824, -3.23715],
    i: "🏭",
    set: "adult",
    category: "history",
    zone: "Industrial",
    event: 'The "Iron King" Slag Fall',
  },
  {
    id: "hist_013",
    n: "Shipyard Gantry 4",
    l: [54.10452, -3.23412],
    i: "⛓️",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: "The 1922 Cable Snap Tragedy",
  },
  {
    id: "hist_014",
    n: "The Basin (Docks)",
    l: [54.10725, -3.22415],
    i: "🌊",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: "The 1901 Silent Drowning",
  },
  {
    id: "hist_015",
    n: "Anchor Point (Ramsden)",
    l: [54.104918, -3.214067],
    i: "⚓",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: "The Sunken Men Memorial",
  },
  {
    id: "hist_016",
    n: "Graving Dock Wall",
    l: [54.112764, -3.241016],
    i: "👻",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: 'The "Hull Tapper" Ghost Site',
  },
  {
    id: "hist_017",
    n: "Slag Bank (East Side)",
    l: [54.12902, -3.240205],
    i: "🧪",
    set: "adult",
    category: "history",
    zone: "Industrial",
    event: 'The "Chemical Glow" Mark',
  },
  {
    id: "hist_018",
    n: "Old Rope Works",
    l: [54.10852, -3.22141],
    i: "🪢",
    set: "adult",
    category: "history",
    zone: "Industrial",
    event: 'Child Labor "Hemp Mark" Site',
  },
  {
    id: "hist_019",
    n: "Heavy Plant Shop",
    l: [54.10552, -3.23121],
    i: "🔨",
    set: "adult",
    category: "history",
    zone: "Industrial",
    event: "The Steam Hammer Scream-Muffler",
  },
  {
    id: "hist_020",
    n: "Shipyard Exit",
    l: [54.107344, -3.22906],
    i: "🏃",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: 'The "Yard Run" Panic',
  },
  {
    id: "hist_021",
    n: "Town Hall Square",
    l: [54.11128, -3.228341],
    i: "🏛️",
    set: "adult",
    category: "history",
    zone: "Civic",
    event: '1914 "72-Hour Exile" Site',
  },
  {
    id: "hist_022",
    n: "Magistrates Court",
    l: [54.116518, -3.227096],
    i: "⚖️",
    set: "adult",
    category: "history",
    zone: "Civic",
    event: "The Butcher’s Sentencing Room",
  },
  {
    id: "hist_023",
    n: "Council Chambers",
    l: [54.11125, -3.22831],
    i: "📜",
    set: "adult",
    category: "history",
    zone: "Civic",
    event: '1890 "Land Grab" Vote Site',
  },
  {
    id: "hist_024",
    n: "Old Infirmary (Abbey Rd)",
    l: [54.12052, -3.22314],
    i: "🏚️",
    set: "adult",
    category: "history",
    zone: "Civic",
    event: 'The "Work-or-Die" Poor Law Site',
  },
  {
    id: "hist_025",
    n: "Roose Workhouse",
    l: [54.11452, -3.20141],
    i: "🪦",
    set: "adult",
    category: "history",
    zone: "Outskirts",
    event: "The Unnamed Poor Graves",
  },
  {
    id: "hist_026",
    n: "Isolation Hospital (Old)",
    l: [54.13952, -3.20814],
    i: "☣️",
    set: "adult",
    category: "history",
    zone: "Outskirts",
    event: 'The "Plague Mark" Quarantine',
  },
  {
    id: "hist_027",
    n: "Mayor’s Parlour",
    l: [54.11128, -3.22834],
    i: "👤",
    set: "adult",
    category: "history",
    zone: "Civic",
    event: "1950 Political Execution Memory",
  },
  {
    id: "hist_028",
    n: "Cenotaph Hill",
    l: [54.118174, -3.221973],
    i: "👑",
    set: "adult",
    category: "history",
    zone: "Civic",
    event: "Ancient Bronze King Burial Site",
  },
  {
    id: "hist_029",
    n: "War Memorial (Park)",
    l: [54.11952, -3.21854],
    i: "🪦",
    set: "adult",
    category: "history",
    zone: "Park",
    event: 'The "Erased Name" Scandal',
  },
  {
    id: "hist_030",
    n: "Jubilee Bridge",
    l: [54.10762, -3.24351],
    i: "🌉",
    set: "adult",
    category: "history",
    zone: "Walney/Coastal",
    event: "The Toll Riots Site",
  },
  {
    id: "hist_031",
    n: "Bridge Road Blockade",
    l: [54.10482, -3.23341],
    i: "🚫",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: "1920 Police No-Exit Zone",
  },
  {
    id: "hist_032",
    n: "Town Hall Cellars",
    l: [54.11121, -3.22832],
    i: "⛓️",
    set: "adult",
    category: "history",
    zone: "Civic",
    event: 'Strike Leader "Dark Cell"',
  },
];
