export const ADULT_PINS = [
  // TRUE CRIME
  {
    id: "tc_001",
    n: "2G Brig Street",
    l: [54.11371, -3.218448],
    i: "🔪",
    set: "adult",
    category: "true_crime",
    zone: "Residential",
    event: "The Hammer Murder (Nellie Pearson)",
  },
  {
    id: "tc_002",
    n: "8 Bacchus Street",
    l: [54.113063, -3.237478],
    i: "🔪",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "Lydia Green Murder (The Hoxton Tragedy)",
  },
  {
    id: "tc_003",
    n: "Bacchus St / Hindpool Corner",
    l: [54.114309, -3.235831],
    i: "🔪",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "Joseph Baines Christmas Eve Murder",
  },
  {
    id: "tc_004",
    n: "Forsyth Street (Back Alley)",
    l: [54.114721, -3.23521],
    i: "🩸",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: 'The "Forgotten Baby" Dog Discovery',
  },
  {
    id: "tc_005",
    n: "Marsh St (Salthouse End)",
    l: [54.109267, -3.215243],
    i: "🩸",
    set: "adult",
    category: "true_crime",
    zone: "Residential",
    event: 'The "Salthouse Bundle" Baby Discovery',
  },
  {
    id: "tc_006",
    n: "Barrow Market (Old Site)",
    l: [54.111491, -3.227258],
    i: "🔪",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: "William Miller (The Butcher) Arrest",
  },
  {
    id: "tc_007",
    n: "Berrymede Road",
    l: [54.118912, -3.210445],
    i: "🕵️",
    set: "adult",
    category: "true_crime",
    zone: "Outskirts",
    event: 'The "Jack the Stripper" Connection',
  },
  {
    id: "tc_008",
    n: "Dalton Road (Alley)",
    l: [54.111966, -3.2254],
    i: "⚰️",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: 'The "Hush Money" Execution Spot',
  },
  {
    id: "tc_009",
    n: "The Strand (Waterfront)",
    l: [54.110245, -3.23158],
    i: "⚰️",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Smuggler’s End Execution",
  },
  {
    id: "tc_010",
    n: "Greengate Street",
    l: [54.112795, -3.220397],
    i: "🔪",
    set: "adult",
    category: "true_crime",
    zone: "Residential",
    event: "The Shilling Robbery Murder Site",
  },
  {
    id: "tc_011",
    n: "Marsh Street (Middle)",
    l: [54.112047, -3.217027],
    i: "⚔️",
    set: "adult",
    category: "true_crime",
    zone: "Residential",
    event: 'The "Knife & Steel" Riot of 1890',
  },
  {
    id: "tc_012",
    n: "Duke Street (Lower)",
    l: [54.110031, -3.225251],
    i: "🕵️",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: 'The "Gentleman Burglar" Hideout',
  },
  {
    id: "tc_013",
    n: "Hoxton Slums (Hindpool)",
    l: [54.11405, -3.23652],
    i: "⚔️",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: 'The Bedroom Riot / "Hot Bed" Fight',
  },
  {
    id: "tc_014",
    n: "Custom House / Hindpool Rd",
    l: [54.112827, -3.233416],
    i: "🩸",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: 'The "Blood Cobbles" Riot Site',
  },
  {
    id: "tc_015",
    n: "Railway Hotel (Old Site)",
    l: [54.115712, -3.228225],
    i: "☠️",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: "The Barrow Poisoning Mystery",
  },
  {
    id: "tc_016",
    n: "Hindpool (Tiger Mural)",
    l: [54.117359, -3.23648],
    i: "🚫",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: 'The Police "No-Go" Boundary',
  },
  {
    id: "tc_017",
    n: "Old Police Station",
    l: [54.11118, -3.227026],
    i: "🚔",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: 'The "Peelers" Siege Site',
  },
  {
    id: "tc_018",
    n: "Piel Castle (Dungeon)",
    l: [54.062336, -3.173362],
    i: "⛓️",
    set: "adult",
    category: "true_crime",
    zone: "Abbey/Ruins",
    event: "The Lambert Simnel Rebel Site",
  },
  {
    id: "tc_019",
    n: "The Ship Inn (Piel)",
    l: [54.064046, -3.172852],
    i: "💰",
    set: "adult",
    category: "true_crime",
    zone: "Walney/Coastal",
    event: "The Shipwreck Gold Secret",
  },
  {
    id: "tc_020",
    n: "Walney West Shore",
    l: [54.11621, -3.27253],
    i: "🕯️",
    set: "adult",
    category: "true_crime",
    zone: "Walney/Coastal",
    event: 'The "Wreckers" False Lantern Site',
  },
  {
    id: "tc_021",
    n: "Lifeboat Station (Old)",
    l: [54.064046, -3.172852],
    i: "⚓",
    set: "adult",
    category: "true_crime",
    zone: "Walney/Coastal",
    event: "The 1890 Crew Tragedy",
  },
  {
    id: "tc_022",
    n: "Cornwallis St (Walls)",
    l: [54.111792, -3.228755],
    i: "🪓",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: 'The Convict "V" Markings',
  },
  {
    id: "tc_023",
    n: "Hindpool / Abbey Corner",
    l: [54.1142, -3.230979],
    i: "🍞",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: "The Loaf of Bread Murder",
  },

  {
    id: "tc_024",
    n: "Salthouse Marshes",
    l: [54.1021, -3.2314],
    i: "🔪",
    set: "adult",
    category: "true_crime",
    zone: "Coastal",
    event: "The Salthouse Flayer",
  },
  {
    id: "tc_025",
    n: "Ironworks Block",
    l: [54.1125, -3.2268],
    i: "🔥",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Hindpool Furnace",
  },
  {
    id: "tc_026",
    n: "High Street Butcher",
    l: [54.1193, -3.2711],
    i: "🪝",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: "The High Street Hook",
  },
  {
    id: "tc_027",
    n: "Devonshire Dock Crane",
    l: [54.1044, -3.2301],
    i: "🏗️",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Wire-Snap Massacre",
  },
  {
    id: "tc_028",
    n: "Hindpool Cellars",
    l: [54.1172, -3.2341],
    i: "🐀",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Rat-Trap Cellar",
  },
  {
    id: "tc_029",
    n: "Abbey Road Church Wall",
    l: [54.1143, -3.2313],
    i: "🪚",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: "The Sawed Steward",
  },
  {
    id: "tc_030",
    n: "Ironworks Lime Vat",
    l: [54.1082, -3.2261],
    i: "🧪",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Caustic Vat",
  },
  {
    id: "tc_031",
    n: "Gantry Crane Cogs",
    l: [54.1092, -3.2398],
    i: "⚙️",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Apprentice's Gear",
  },
  {
    id: "tc_032",
    n: "Greengate St Bedroom",
    l: [54.1127, -3.2203],
    i: "🔨",
    set: "adult",
    category: "true_crime",
    zone: "Residential",
    event: "The Red-Lace Bride",
  },
  {
    id: "tc_033",
    n: "Salthouse Mudflats",
    l: [54.1092, -3.2152],
    i: "🦷",
    set: "adult",
    category: "true_crime",
    zone: "Coastal",
    event: "The Mudflat Biter",
  },
  {
    id: "tc_034",
    n: "Submarine Engine Room",
    l: [54.1015, -3.2332],
    i: "🌡️",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Boiler-Room Ghost",
  },
  {
    id: "tc_035",
    n: "Liner Deck Slipway",
    l: [54.1015, -3.242],
    i: "📌",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Riveting-Gun Hit",
  },
  {
    id: "tc_036",
    n: "Michaelson Bridge Gears",
    l: [54.1035, -3.2365],
    i: "🌉",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Michaelson Mangling",
  },
  {
    id: "tc_037",
    n: "Roose Workhouse Well",
    l: [54.125, -3.195],
    i: "🕳️",
    set: "adult",
    category: "true_crime",
    zone: "Outskirts",
    event: "The Workhouse Well",
  },
  {
    id: "tc_038",
    n: "Torpedo Tube 1",
    l: [54.1002, -3.2455],
    i: "🚀",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Torpedo-Tube Stowaway",
  },
  {
    id: "tc_039",
    n: "Duke Street Bench",
    l: [54.11, -3.2252],
    i: "🪑",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: "The Duke Street Scalpel",
  },
  {
    id: "tc_040",
    n: "Scrapyard Hull",
    l: [54.1021, -3.2395],
    i: "🏗️",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Bilgewater Burial",
  },
  {
    id: "tc_041",
    n: "Shipyard Hostel Laundry",
    l: [54.1055, -3.2382],
    i: "🧼",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Laundress's Lye",
  },
  {
    id: "tc_042",
    n: "Munitions Factory Site",
    l: [54.1189, -3.2104],
    i: "🧨",
    set: "adult",
    category: "true_crime",
    zone: "Outskirts",
    event: "The Shell-Filler's Glow",
  },
  {
    id: "tc_043",
    n: "Officer's Quarters",
    l: [54.116, -3.2315],
    i: "🧵",
    set: "adult",
    category: "true_crime",
    zone: "Residential",
    event: "The Seamstress's Needle",
  },
  {
    id: "tc_044",
    n: "Shipyard Archives",
    l: [54.1143, -3.2313],
    i: "⌨️",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: "The Typist's Ribbon",
  },
  {
    id: "tc_045",
    n: "Shipyard Canteen",
    l: [54.107, -3.232],
    i: "🥣",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Canteen's Arsenic",
  },
  {
    id: "tc_046",
    n: "Dockside Pub Cellar",
    l: [54.1035, -3.2365],
    i: "🍺",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Barmaid's Cellar",
  },
  {
    id: "tc_047",
    n: "Duke Street Window",
    l: [54.1135, -3.2295],
    i: "👒",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: "The Milliner's Pin",
  },
  {
    id: "tc_048",
    n: "Hindpool Gutter",
    l: [54.118, -3.2355],
    i: "👜",
    set: "adult",
    category: "true_crime",
    zone: "Residential",
    event: "The Midwife's Bag",
  },
  {
    id: "tc_049",
    n: "Dalton Road Florist",
    l: [54.1152, -3.2255],
    i: "🌹",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: "The Florist's Thorns",
  },
  {
    id: "tc_050",
    n: "Director's Grand Stairs",
    l: [54.1185, -3.224],
    i: "📓",
    set: "adult",
    category: "true_crime",
    zone: "Residential",
    event: "The Governess's Fall",
  },
  {
    id: "tc_051",
    n: "Walney Lighthouse",
    l: [54.0494, -3.1772],
    i: "🕯️",
    set: "adult",
    category: "true_crime",
    zone: "Walney/Coastal",
    event: "The Lighthouse Keeper's Bride",
  },
  {
    id: "tc_052",
    n: "Railway Signal Box",
    l: [54.1198, -3.2185],
    i: "🧣",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: "The Signalman's Box",
  },
  {
    id: "tc_053",
    n: "Industrial Laundry Site",
    l: [54.1132, -3.2381],
    i: "🧺",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Laundress's Wringer",
  },
  {
    id: "tc_054",
    n: "Furness Abbey Crypt",
    l: [54.1378, -3.1982],
    i: "⛪",
    set: "adult",
    category: "true_crime",
    zone: "Abbey/Ruins",
    event: "The Abbey Crypt Girl",
  },
  {
    id: "tc_055",
    n: "Abbey Road Telegraph",
    l: [54.1155, -3.2272],
    i: "⚡",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: "The Telegraph Wire",
  },
  {
    id: "tc_056",
    n: "Barrow Island Tenement",
    l: [54.1042, -3.2351],
    i: "🌹",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Velvet Strangler",
  },
  {
    id: "tc_057",
    n: "Dock Boarding House",
    l: [54.1085, -3.2324],
    i: "🪵",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Shipyard Nursery",
  },
  {
    id: "tc_058",
    n: "Dockside Ice-House",
    l: [54.1008, -3.2392],
    i: "❄️",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Ice-House Hook",
  },
  {
    id: "tc_059",
    n: "Hindpool Attic",
    l: [54.1165, -3.2368],
    i: "✂️",
    set: "adult",
    category: "true_crime",
    zone: "Residential",
    event: "The Seamstress's Scissor",
  },
  {
    id: "tc_060",
    n: "Ramsey Ferry Dock",
    l: [54.1062, -3.2312],
    i: "🛢️",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Dockside Barrel",
  },
  {
    id: "tc_061",
    n: "Launchway Ballast Tank",
    l: [54.1018, -3.2452],
    i: "🤿",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Boiler-Suit Babe",
  },
  {
    id: "tc_062",
    n: "Vickers Gate Track",
    l: [54.1105, -3.2385],
    i: "🛤️",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Railway Sleeper's Wife",
  },
  {
    id: "tc_063",
    n: "Kitchen Grinder Site",
    l: [54.1052, -3.2378],
    i: "🥩",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Canteen Carver",
  },
  {
    id: "tc_064",
    n: "Technical Drawing Vault",
    l: [54.1065, -3.2342],
    i: "📜",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Blueprint Binder",
  },
  {
    id: "tc_065",
    n: "The Rope-Walk",
    l: [54.1088, -3.2305],
    i: "🪢",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Rope-Walk Strangler",
  },
  {
    id: "tc_066",
    n: "Duke St Lab Shop",
    l: [54.1132, -3.2288],
    i: "🧴",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: "The Apothecary's Sister",
  },
  {
    id: "tc_067",
    n: "Town Hall Balcony",
    l: [54.1124, -3.2265],
    i: "🕙",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: "The Clocktower Maiden",
  },
  {
    id: "tc_068",
    n: "Shipyard Shed 12",
    l: [54.1075, -3.2392],
    i: "📍",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Riveter's Daughter",
  },
  {
    id: "tc_069",
    n: "Foundry Sand Floor",
    l: [54.1085, -3.2258],
    i: "🔩",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Foundry-Floor Lady",
  },
  {
    id: "tc_070",
    n: "Shipyard Alleyway",
    l: [54.1098, -3.2372],
    i: "🧥",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Mackintosh Widow",
  },
  {
    id: "tc_071",
    n: "Abbotsmead Hostel",
    l: [54.1205, -3.2082],
    i: "🩹",
    set: "adult",
    category: "true_crime",
    zone: "Outskirts",
    event: "The Shell-Shocked Nurse",
  },
  {
    id: "tc_072",
    n: "Barrow Exchange",
    l: [54.1138, -3.2275],
    i: "📞",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: "The Telephone Exchange",
  },
  {
    id: "tc_073",
    n: "Drawing Office Office",
    l: [54.1072, -3.2318],
    i: "🍵",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Canteen's Glass",
  },
  {
    id: "tc_074",
    n: "Devonshire Gantry",
    l: [54.1046, -3.2298],
    i: "👰",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Gantry Bride",
  },
  {
    id: "tc_075",
    n: "Hartington St Chute",
    l: [54.1162, -3.2318],
    i: "🌑",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: "The Coal-Chute Girl",
  },
  {
    id: "tc_076",
    n: "Barrow Textile Mill",
    l: [54.1205, -3.221],
    i: "🧶",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: "The Weaver's Bobbin",
  },
  {
    id: "tc_077",
    n: "Dock Salt Sheds",
    l: [54.1021, -3.2314],
    i: "🧂",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Shipyard's Salt-Doll",
  },
  {
    id: "tc_078",
    n: "Dalton Road Shop",
    l: [54.1152, -3.2255],
    i: "🌀",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: "The Florist's Wire",
  },
  {
    id: "tc_079",
    n: "Drawing Office Vat",
    l: [54.107, -3.232],
    i: "✒️",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Ink-Well Widow",
  },
  {
    id: "tc_080",
    n: "Ramsden Square Garden",
    l: [54.1141, -3.2285],
    i: "🎭",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: "The mackintosh mask",
  },
  {
    id: "tc_081",
    n: "Main Foundry Floor",
    l: [54.1082, -3.2261],
    i: "🔩",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Foundry Matron",
  },
  {
    id: "tc_082",
    n: "Post Office Station",
    l: [54.1141, -3.2285],
    i: "📟",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: "The Telegraph Girl's Code",
  },
  {
    id: "tc_083",
    n: "Barrow Island Canteen",
    l: [54.1055, -3.2382],
    i: "🍲",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Canteen's Copper",
  },
  {
    id: "tc_084",
    n: "Salthouse Storage",
    l: [54.1021, -3.2314],
    i: "💎",
    set: "adult",
    category: "true_crime",
    zone: "Coastal",
    event: "The Shipyard's Salt-Doll (II)",
  },
  {
    id: "tc_085",
    n: "Slipway Four Hull",
    l: [54.1015, -3.242],
    i: "🔨",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Riveter's Mistress",
  },
  {
    id: "tc_086",
    n: "Blake Street Alley",
    l: [54.1172, -3.2341],
    i: "🩹",
    set: "adult",
    category: "true_crime",
    zone: "Residential",
    event: "The mackintosh mask (II)",
  },
  {
    id: "tc_087",
    n: "Barrow Island Vault",
    l: [54.1068, -3.2335],
    i: "📔",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Blueprint Widow",
  },
  {
    id: "tc_088",
    n: "Town Hall Drive-Wheel",
    l: [54.1126, -3.2268],
    i: "🕒",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: "The Clocktower Maiden (II)",
  },
  {
    id: "tc_089",
    n: "Devonshire Gantry Crane",
    l: [54.1044, -3.2301],
    i: "👰",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Gantry Bride (II)",
  },
  {
    id: "tc_090",
    n: "Submarine Test Dock",
    l: [54.1002, -3.2455],
    i: "⚓",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Ballast Tank Girl",
  },
  {
    id: "tc_091",
    n: "Flax Mill Site",
    l: [54.1205, -3.221],
    i: "🧵",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: "The Weaver's Bobbin (II)",
  },
  {
    id: "tc_092",
    n: "Duke Street Pharmacy",
    l: [54.1135, -3.2295],
    i: "🏺",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: "The Apothecary's Sister (II)",
  },
  {
    id: "tc_093",
    n: "Merchant House Chute",
    l: [54.116, -3.2315],
    i: "🪵",
    set: "adult",
    category: "true_crime",
    zone: "Residential",
    event: "The Coal-Chute Maid",
  },
  {
    id: "tc_094",
    n: "Dalton Road Gear",
    l: [54.1152, -3.2255],
    i: "⚙️",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: "The Florist's Wire (II)",
  },
  {
    id: "tc_095",
    n: "Bridge Road Office",
    l: [54.107, -3.232],
    i: "✒️",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Ink-Well Widow (II)",
  },
  {
    id: "tc_096",
    n: "Abbey Road Villa",
    l: [54.1185, -3.224],
    i: "🪜",
    set: "adult",
    category: "true_crime",
    zone: "Residential",
    event: "The Governess's Fall (II)",
  },
  {
    id: "tc_097",
    n: "Michaelson Road Cellar",
    l: [54.1035, -3.2365],
    i: "🛢️",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Barmaid's Barrel (II)",
  },
  {
    id: "tc_098",
    n: "Cavendish St Window",
    l: [54.113, -3.2305],
    i: "📌",
    set: "adult",
    category: "true_crime",
    zone: "Civic",
    event: "The Milliner's Pin (II)",
  },
  {
    id: "tc_099",
    n: "Foundry Street Slums",
    l: [54.118, -3.2355],
    i: "👜",
    set: "adult",
    category: "true_crime",
    zone: "Residential",
    event: "The Midwife's Bag (II)",
  },
  {
    id: "tc_100",
    n: "Ramsden Dock Launchway",
    l: [54.101, -3.2435],
    i: "⛓️",
    set: "adult",
    category: "true_crime",
    zone: "Docks",
    event: "The Final Launch",
  },

  // CONSPIRACY
  {
    id: "con_001",
    n: "DDH Hall (BAE Systems)",
    l: [54.109263, -3.239847],
    i: "🛸",
    set: "adult",
    category: "conspiracy",
    zone: "Docks",
    event: 'The "Phantom Crane" Suicide Site',
  },
  {
    id: "con_002",
    n: "Steel Company HQ",
    l: [54.11252, -3.22684],
    i: "📁",
    set: "adult",
    category: "conspiracy",
    zone: "Civic",
    event: 'The "Silence Money" Envelopes',
  },
  {
    id: "con_003",
    n: "The Jetty (Walney)",
    l: [54.119381, -3.271118],
    i: "🌫️",
    set: "adult",
    category: "conspiracy",
    zone: "Walney/Coastal",
    event: 'The Stowaway "Return" Point',
  },
  {
    id: "con_004",
    n: "Buoy Wharf",
    l: [54.10214, -3.23952],
    i: "🛸",
    set: "adult",
    category: "conspiracy",
    zone: "Docks",
    event: 'The "Floating Mystery" Tie-up',
  },
  {
    id: "con_005",
    n: "Submarine Slipway (Old)",
    l: [54.10154, -3.23321],
    i: "🕵️",
    set: "adult",
    category: "conspiracy",
    zone: "Docks",
    event: 'The Armed Guard "Spy" Post',
  },
  {
    id: "con_006",
    n: "The Forum (Duke St)",
    l: [54.112121, -3.227529],
    i: "☣️",
    set: "adult",
    category: "conspiracy",
    zone: "Civic",
    event: "2002 Legionnaires' Outbreak",
  },
  {
    id: "con_007",
    n: "Furness General Hospital",
    l: [54.136744, -3.210349],
    i: "🏥",
    set: "adult",
    category: "conspiracy",
    zone: "Civic",
    event: "Maternity Cover-up Scandal",
  },
  {
    id: "con_008",
    n: "CQC Office (Old Site)",
    l: [54.11352, -3.22414],
    i: "🗂️",
    set: "adult",
    category: "conspiracy",
    zone: "Civic",
    event: 'The "Deleted File" Shredder Room',
  },
  {
    id: "con_009",
    n: "Public Baths (Abbey Rd)",
    l: [54.114949, -3.229983],
    i: "🤝",
    set: "adult",
    category: "conspiracy",
    zone: "Civic",
    event: 'The "Grey Contract" Meeting Room',
  },
  {
    id: "con_010",
    n: "Barrow Library",
    l: [54.114356, -3.231339],
    i: "📚",
    set: "adult",
    category: "conspiracy",
    zone: "Civic",
    event: '1945 "Red File" Hiding Spot',
  },
  {
    id: "con_011",
    n: "Customs House",
    l: [54.112978, -3.233288],
    i: "💼",
    set: "adult",
    category: "conspiracy",
    zone: "Civic",
    event: 'The "Blind Eye" Bribe Spot',
  },
  {
    id: "con_012",
    n: "Walney Airfield Bunker",
    l: [54.120865, -3.256751],
    i: "🪖",
    set: "adult",
    category: "conspiracy",
    zone: "Walney/Coastal",
    event: 'Last Stand "Suicide" Bunker',
  },
  {
    id: "con_013",
    n: "West Shore Tower",
    l: [54.13052, -3.27014],
    i: "👁️",
    set: "adult",
    category: "conspiracy",
    zone: "Walney/Coastal",
    event: "Government Town-Watch Post",
  },
  {
    id: "con_014",
    n: "Municipal Buildings",
    l: [54.11152, -3.22854],
    i: "🔥",
    set: "adult",
    category: "conspiracy",
    zone: "Civic",
    event: "Slum Clearance Evidence Burn",
  },
  {
    id: "con_015",
    n: "Record Office (Duke St)",
    l: [54.11184, -3.22685],
    i: "🗺️",
    set: "adult",
    category: "conspiracy",
    zone: "Civic",
    event: 'The "Secret Map" Archive',
  },
  {
    id: "con_016",
    n: "Main Yard Entrance",
    l: [54.10921, -3.23941],
    i: "🚧",
    set: "adult",
    category: "conspiracy",
    zone: "Docks",
    event: "Government ID Check Post",
  },
  {
    id: "con_017",
    n: "Telegram Office",
    l: [54.11142, -3.22784],
    i: "📡",
    set: "adult",
    category: "conspiracy",
    zone: "Civic",
    event: '"Hollow Knock" Message Center',
  },
  {
    id: "con_018",
    n: "Dock Gate 1",
    l: [54.10821, -3.22741],
    i: "🚢",
    set: "adult",
    category: "conspiracy",
    zone: "Docks",
    event: 'Forbidden "Gov Property" Zone',
  },
  {
    id: "con_019",
    n: "Ghost Path Gate (Abbey Rd)",
    l: [54.140075, -3.200542],
    i: "👻",
    set: "adult",
    category: "conspiracy",
    zone: "Abbey/Ruins",
    event: 'The "White Lady" Waiting Spot',
  },

  // HISTORY
  {
    id: "hist_001",
    n: "Dock Museum (Graving)",
    l: [54.1124, -3.240276],
    i: "⚙️",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: "The Unsolved Riveter Murder",
  },
  {
    id: "hist_002",
    n: "Bridge Road Gates",
    l: [54.104823, -3.23345],
    i: "📜",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: 'WWI "White Feather" Shaming Site',
  },
  {
    id: "hist_003",
    n: "Michaelson Road",
    l: [54.105043, -3.230699],
    i: "🏭",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: "Asbestos Alley (The White Dust)",
  },
  {
    id: "hist_004",
    n: "North Slag Bank",
    l: [54.13315, -3.24307],
    i: "⛰️",
    set: "adult",
    category: "history",
    zone: "Industrial",
    event: 'The "Disappearance" Molten Hole',
  },
  {
    id: "hist_005",
    n: "Devonshire Dock",
    l: [54.102709, -3.232435],
    i: "⚓",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: 'The "Screaming Sub" Launch Site',
  },
  {
    id: "hist_006",
    n: "Shipyard Main Clock",
    l: [54.10651, -3.23214],
    i: "🕰️",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: 'The "Death Clock" (Shift Accidents)',
  },
  {
    id: "hist_007",
    n: "Old Ironworks Site",
    l: [54.11958, -3.23852],
    i: "🏭",
    set: "adult",
    category: "history",
    zone: "Industrial",
    event: "The Chimney Fall Tragedy",
  },
  {
    id: "hist_008",
    n: "North Gate (Bridge Rd)",
    l: [54.109439, -3.239407],
    i: "🛠️",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: "Young Charles’ Wagon Tragedy",
  },
  {
    id: "hist_009",
    n: "Barrow Island Blocks",
    l: [54.10152, -3.22814],
    i: "🏚️",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: 'The 3,000-man "Shanty" Slum Site',
  },
  {
    id: "hist_010",
    n: "Engine Sheds (Rail)",
    l: [54.11181, -3.21854],
    i: "💥",
    set: "adult",
    category: "history",
    zone: "Industrial",
    event: "The 1910 Boiler Explosion",
  },
  {
    id: "hist_011",
    n: "Vulcan Works (Hindpool)",
    l: [54.11582, -3.23412],
    i: "🔥",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: "The 1892 Riot Fire Marks",
  },
  {
    id: "hist_012",
    n: "Blast Furnace Site",
    l: [54.11824, -3.23715],
    i: "🏭",
    set: "adult",
    category: "history",
    zone: "Industrial",
    event: 'The "Iron King" Slag Fall',
  },
  {
    id: "hist_013",
    n: "Shipyard Gantry 4",
    l: [54.10452, -3.23412],
    i: "⛓️",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: "The 1922 Cable Snap Tragedy",
  },
  {
    id: "hist_014",
    n: "The Basin (Docks)",
    l: [54.10725, -3.22415],
    i: "🌊",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: "The 1901 Silent Drowning",
  },
  {
    id: "hist_015",
    n: "Anchor Point (Ramsden)",
    l: [54.104918, -3.214067],
    i: "⚓",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: "The Sunken Men Memorial",
  },
  {
    id: "hist_016",
    n: "Graving Dock Wall",
    l: [54.112764, -3.241016],
    i: "👻",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: 'The "Hull Tapper" Ghost Site',
  },
  {
    id: "hist_017",
    n: "Slag Bank (East Side)",
    l: [54.12902, -3.240205],
    i: "🧪",
    set: "adult",
    category: "history",
    zone: "Industrial",
    event: 'The "Chemical Glow" Mark',
  },
  {
    id: "hist_018",
    n: "Old Rope Works",
    l: [54.10852, -3.22141],
    i: "🪢",
    set: "adult",
    category: "history",
    zone: "Industrial",
    event: 'Child Labor "Hemp Mark" Site',
  },
  {
    id: "hist_019",
    n: "Heavy Plant Shop",
    l: [54.10552, -3.23121],
    i: "🔨",
    set: "adult",
    category: "history",
    zone: "Industrial",
    event: "The Steam Hammer Scream-Muffler",
  },
  {
    id: "hist_020",
    n: "Shipyard Exit",
    l: [54.107344, -3.22906],
    i: "🏃",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: 'The "Yard Run" Panic',
  },
  {
    id: "hist_021",
    n: "Town Hall Square",
    l: [54.11128, -3.228341],
    i: "🏛️",
    set: "adult",
    category: "history",
    zone: "Civic",
    event: '1914 "72-Hour Exile" Site',
  },
  {
    id: "hist_022",
    n: "Magistrates Court",
    l: [54.116518, -3.227096],
    i: "⚖️",
    set: "adult",
    category: "history",
    zone: "Civic",
    event: "The Butcher’s Sentencing Room",
  },
  {
    id: "hist_023",
    n: "Council Chambers",
    l: [54.11125, -3.22831],
    i: "📜",
    set: "adult",
    category: "history",
    zone: "Civic",
    event: '1890 "Land Grab" Vote Site',
  },
  {
    id: "hist_024",
    n: "Old Infirmary (Abbey Rd)",
    l: [54.12052, -3.22314],
    i: "🏚️",
    set: "adult",
    category: "history",
    zone: "Civic",
    event: 'The "Work-or-Die" Poor Law Site',
  },
  {
    id: "hist_025",
    n: "Roose Workhouse",
    l: [54.11452, -3.20141],
    i: "🪦",
    set: "adult",
    category: "history",
    zone: "Outskirts",
    event: "The Unnamed Poor Graves",
  },
  {
    id: "hist_026",
    n: "Isolation Hospital (Old)",
    l: [54.13952, -3.20814],
    i: "☣️",
    set: "adult",
    category: "history",
    zone: "Outskirts",
    event: 'The "Plague Mark" Quarantine',
  },
  {
    id: "hist_027",
    n: "Mayor’s Parlour",
    l: [54.11128, -3.22834],
    i: "👤",
    set: "adult",
    category: "history",
    zone: "Civic",
    event: "1950 Political Execution Memory",
  },
  {
    id: "hist_028",
    n: "Cenotaph Hill",
    l: [54.118174, -3.221973],
    i: "👑",
    set: "adult",
    category: "history",
    zone: "Civic",
    event: "Ancient Bronze King Burial Site",
  },
  {
    id: "hist_029",
    n: "War Memorial (Park)",
    l: [54.11952, -3.21854],
    i: "🪦",
    set: "adult",
    category: "history",
    zone: "Park",
    event: 'The "Erased Name" Scandal',
  },
  {
    id: "hist_030",
    n: "Jubilee Bridge",
    l: [54.10762, -3.24351],
    i: "🌉",
    set: "adult",
    category: "history",
    zone: "Walney/Coastal",
    event: "The Toll Riots Site",
  },
  {
    id: "hist_031",
    n: "Bridge Road Blockade",
    l: [54.10482, -3.23341],
    i: "🚫",
    set: "adult",
    category: "history",
    zone: "Docks",
    event: "1920 Police No-Exit Zone",
  },
  {
    id: "hist_032",
    n: "Town Hall Cellars",
    l: [54.11121, -3.22832],
    i: "⛓️",
    set: "adult",
    category: "history",
    zone: "Civic",
    event: 'Strike Leader "Dark Cell"',
  },
];
